[workspace]
resolver = "2"
default-members = ["kernel"]
members = [
    "libraries/kernel_user_link",
    "kernel",
    "userspace/init", "userspace/shell", "libraries/increasing_heap_allocator", "libraries/user_std",
]
