[env]
CARGO_BUILD_TARGET = "${CARGO_MAKE_WORKING_DIRECTORY}/x86-64-os.json"
KERNEL_PATH = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/x86-64-os/${PROFILE}/kernel"
GRUB_CFG_PATH = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/kernel/grub.cfg"
GRUB_PATH = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/${PROFILE}/grub"

[tasks.build]
command = "cargo"
condition= {files_modified = {input=["${CARGO_MAKE_WORKING_DIRECTORY}/src/**/*", "${CARGO_MAKE_WORKING_DIRECTORY}/Cargo.toml"], output=["${KERNEL_PATH}"]}}
args = ["build", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "-Z", "build-std=core,alloc,compiler_builtins", "-Z", "build-std-features=compiler-builtins-mem"]

[tasks.iso_create_grub]
private = true
condition= {files_not_exist = ["${GRUB_PATH}/boot/grub"]}
command = "mkdir"
args = ["-p", "${GRUB_PATH}/boot/grub"]

[tasks.iso_copy_kernel]
private = true
condition= {files_modified = {input=["${KERNEL_PATH}"], output=["${GRUB_PATH}/boot/kernel"]}}
dependencies = ["iso_create_grub", "build"]
command = "cp"
args = ["${KERNEL_PATH}", "${GRUB_PATH}/boot/kernel"]

[tasks.iso_copy_grub_cfg]
private = true
condition= {files_modified = {input=["${GRUB_CFG_PATH}"], output=["${GRUB_PATH}/boot/grub/grub.cfg"]}}
dependencies = ["iso_create_grub"]
command = "cp"
args = ["${GRUB_CFG_PATH}", "${GRUB_PATH}/boot/grub/grub.cfg"]

[tasks.iso]
condition= {files_modified = {input=["${GRUB_PATH}/**/*"], output=["${ISO_PATH}"]}}
dependencies = ["iso_copy_grub_cfg", "iso_copy_kernel"]
command = "grub-mkrescue"
args = ["-o", "${ISO_PATH}", "${GRUB_PATH}"]

