# Use different pre-set defaults than the global defaults.
#
# See `src/bootstrap/defaults` for more information.
# Note that this has no default value (x.py uses the defaults in `config.example.toml`).
# profile = 'dist'
change-id = 102579

[llvm]
download-ci-llvm = true
# targets = "X86"

[build]
target = ["x86_64-unknown-emerald", "x86_64-unknown-linux-gnu"]
docs = false

# Arguments passed to the `./configure` script, used during distcheck. You
# probably won't fill this in but rather it's filled in by the `./configure`
# script. Useful for debugging.
configure-args = []

[install]
prefix = "../toolchain"
sysconfdir = "../toolchain/etc"

[rust]
lld = true

[target.x86_64-unknown-linux-gnu]

[dist]

