[toolchain]
# Make sure you have built the toolchain or downloaded prebuilt one
# check README.md or the book (https://amjad.alsharafi.dev/Emerald/userspace/index.html) for more details
path = "../extern/toolchain"